// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/ProductList"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateProductData"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/ID"
            }
          },
          "400": {
            "description": "400 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "404 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ResponseData": {
      "anyOf": [
        {
          "$ref": "#/definitions/Product",
          "title": "ResponseData"
        },
        {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "ResponseData.[]"
          },
          "title": "ResponseData.[]",
          "type": "array"
        }
      ],
      "title": "ResponseData"
    },
    "BodyData": {
      "anyOf": [
        {
          "$ref": "#/definitions/ResponseData",
          "title": "BodyData"
        },
        {
          "properties": {
            "message": {
              "title": "BodyData.message",
              "type": "string"
            }
          },
          "required": [
            "message"
          ],
          "additionalProperties": false,
          "title": "BodyData",
          "type": "object"
        }
      ],
      "title": "BodyData"
    },
    "ErrorResponse": {
      "properties": {
        "message": {
          "title": "ErrorResponse.message",
          "type": "string"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    },
    "CreateProductData": {
      "properties": {
        "title": {
          "title": "CreateProductData.title",
          "type": "string"
        },
        "description": {
          "title": "CreateProductData.description",
          "type": "string"
        },
        "price": {
          "title": "CreateProductData.price",
          "type": "number"
        },
        "count": {
          "title": "CreateProductData.count",
          "type": "number"
        }
      },
      "required": [
        "title"
      ],
      "additionalProperties": false,
      "title": "CreateProductData",
      "type": "object"
    },
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductList": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "ProductList.[]"
      },
      "title": "ProductList.[]",
      "type": "array"
    },
    "ID": {
      "properties": {
        "id": {
          "title": "ID.id",
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false,
      "title": "ID",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};